// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6J-VwYwJGu2t3u_CnGIqzqoY7lNSPU2o',
    appId: '1:851797641213:web:5b38ee0fcaf3cf7ddbbb94',
    messagingSenderId: '851797641213',
    projectId: 'treino-app-1e925',
    authDomain: 'treino-app-1e925.firebaseapp.com',
    databaseURL: 'https://treino-app-1e925-default-rtdb.firebaseio.com',
    storageBucket: 'treino-app-1e925.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa41v7YQCAktOl2mEsNRNzdOFJZtyg-W0',
    appId: '1:851797641213:android:649e2689059f4d13dbbb94',
    messagingSenderId: '851797641213',
    projectId: 'treino-app-1e925',
    databaseURL: 'https://treino-app-1e925-default-rtdb.firebaseio.com',
    storageBucket: 'treino-app-1e925.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuLtrwmogbiI1PVxFfgRSKr562SxH0sDg',
    appId: '1:851797641213:ios:6f8ff07d326b885cdbbb94',
    messagingSenderId: '851797641213',
    projectId: 'treino-app-1e925',
    databaseURL: 'https://treino-app-1e925-default-rtdb.firebaseio.com',
    storageBucket: 'treino-app-1e925.firebasestorage.app',
    iosBundleId: 'com.example.treinoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuLtrwmogbiI1PVxFfgRSKr562SxH0sDg',
    appId: '1:851797641213:ios:6f8ff07d326b885cdbbb94',
    messagingSenderId: '851797641213',
    projectId: 'treino-app-1e925',
    databaseURL: 'https://treino-app-1e925-default-rtdb.firebaseio.com',
    storageBucket: 'treino-app-1e925.firebasestorage.app',
    iosBundleId: 'com.example.treinoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6J-VwYwJGu2t3u_CnGIqzqoY7lNSPU2o',
    appId: '1:851797641213:web:61078d99f3192099dbbb94',
    messagingSenderId: '851797641213',
    projectId: 'treino-app-1e925',
    authDomain: 'treino-app-1e925.firebaseapp.com',
    databaseURL: 'https://treino-app-1e925-default-rtdb.firebaseio.com',
    storageBucket: 'treino-app-1e925.firebasestorage.app',
  );
}
